/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventana;

import Ventana.Curso;
import static Ventana.vAdministrarCursos.contadorCursos;
import static Ventana.vAdministrarCursos.cursos;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class vCrearCurso extends javax.swing.JFrame {

    /**
     * Creates new form CrearProfesor
     */
    public vCrearCurso() {
        initComponents();
        this.setResizable(false);
        cod(tCreditos);

        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tCodigo = new javax.swing.JTextField();
        CrearBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tNombre = new javax.swing.JTextField();
        tCreditos = new javax.swing.JTextField();
        tProfesor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(51, 102, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tCodigo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCodigoActionPerformed(evt);
            }
        });

        CrearBtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        CrearBtn.setText("Crear");
        CrearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Nombre");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Creditos");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Codigo");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("Profesor");

        tNombre.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        tCreditos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCreditosActionPerformed(evt);
            }
        });

        tProfesor.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tProfesorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(5, 5, 5))
                            .addComponent(jLabel4))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CrearBtn)
                .addGap(163, 163, 163))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(CrearBtn)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearBtnActionPerformed
        // TODO add your handling code here:
        String Acodigo = tCodigo.getText();
        String Anombre = tNombre.getText();
        String Acreditos = tCreditos.getText();
        String Aalumnos="0";
        String Aprofesor = tProfesor.getText();
        int cantAlumnos = (int) Math.floor(Math.random() * (80 - 0) + 0);


        
        if(contadorCursos==0){
            
            Curso nuevoCurso = new Curso(Acodigo, Anombre, Acreditos, Aalumnos, Aprofesor);
        int contadorCursos = vAdministrarCursos.contadorCursos;
        
        vAdministrarCursos.cursos[contadorCursos] = nuevoCurso;
        
        vAdministrarCursos.contadorCursos++;
        
        JOptionPane.showMessageDialog(null, "Curso Agregado." , "Aviso" , JOptionPane.INFORMATION_MESSAGE);
        tCodigo.setText("");
        tNombre.setText("");
        tCreditos.setText("");
        tProfesor.setText("");

        tCodigo.requestFocus();
            
        } else{
            boolean abc=true;
            for(int i=0;i<contadorCursos;i++){
                   if((Acodigo.equals(cursos[i].codigo))){
                       JOptionPane.showMessageDialog(null, "El codigo fue registrado." , "Aviso" , JOptionPane.INFORMATION_MESSAGE);
                       abc=false;
                       tCodigo.setText("");
                        tNombre.setText("");
                        tCreditos.setText("");
                        tProfesor.setText("");

                        tCodigo.requestFocus();
                   }}
                if(abc==true){Curso nuevoCurso = new Curso(Acodigo, Anombre, Acreditos, Aalumnos, Aprofesor);
                int contadorCursos = vAdministrarCursos.contadorCursos;
        
                 vAdministrarCursos.cursos[contadorCursos] = nuevoCurso;
        
                  vAdministrarCursos.contadorCursos++;
        
        JOptionPane.showMessageDialog(null, "Curso Agregado." , "Aviso" , JOptionPane.INFORMATION_MESSAGE);
        tCodigo.setText("");
        tNombre.setText("");
        tCreditos.setText("");
        tProfesor.setText("");
        tCodigo.requestFocus();
        
                   
               
        }
        }
        

    }//GEN-LAST:event_CrearBtnActionPerformed

 
    private void tCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tCodigoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.setVisible(false);
        vAdministrarCursos ap = new vAdministrarCursos();
        ap.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void tProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tProfesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tProfesorActionPerformed

    private void tCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCreditosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tCreditosActionPerformed

    /**
     * @param args the command line arguments
     */

    
    private void cod(JTextField a){
        a.addKeyListener(new KeyAdapter(){
            public void keyTyped(KeyEvent e){
                char c= e.getKeyChar();
                String a="m",b="f";
                
                if(Character.isAlphabetic(c)){
                    e.consume();
                }
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CrearBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField tCodigo;
    private javax.swing.JTextField tCreditos;
    private javax.swing.JTextField tNombre;
    private javax.swing.JTextField tProfesor;
    // End of variables declaration//GEN-END:variables
}
