/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventana;

import static Ventana.vAdministrarCursos.cursos;
import static Ventana.vLogin.num2;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.Arrays;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Harold
 */
public class vCursos extends javax.swing.JFrame {
    public static Alumno[] alumnos = new Alumno[300];
    public static int contadorAlumnos;
    /**
     * Creates new form vCursos
     */
    public vCursos() {
        initComponents();
        lCurso.setText(cursos[num2].nombre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ListadoAlumnos = new javax.swing.JTable();
        lCurso = new javax.swing.JLabel();
        Listadooo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListadoActividades = new javax.swing.JTable();
        Listadooo1 = new javax.swing.JLabel();
        Listadooo2 = new javax.swing.JLabel();
        tAcumulado = new javax.swing.JTextField();
        Listadooo3 = new javax.swing.JLabel();
        tAcumulado1 = new javax.swing.JTextField();
        Listadooo4 = new javax.swing.JLabel();
        tAcumulado2 = new javax.swing.JTextField();
        Listadooo5 = new javax.swing.JLabel();
        tAcumulado3 = new javax.swing.JTextField();
        Listadooo6 = new javax.swing.JLabel();
        Listadooo7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        bCargaAlumnos = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ListadoAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Apellido", "Acciones"
            }
        ));
        jScrollPane1.setViewportView(ListadoAlumnos);
        if (ListadoAlumnos.getColumnModel().getColumnCount() > 0) {
            ListadoAlumnos.getColumnModel().getColumn(3).setHeaderValue("Acciones");
        }

        lCurso.setText(".");

        Listadooo.setText("Listado de Alumnos");

        ListadoActividades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Descripcion", "Ponderacion"
            }
        ));
        jScrollPane2.setViewportView(ListadoActividades);

        Listadooo1.setText("Actividades");

        Listadooo2.setText("Acumulado:");

        tAcumulado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tAcumuladoActionPerformed(evt);
            }
        });

        Listadooo3.setText("Crear Actividades:");

        tAcumulado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tAcumulado1ActionPerformed(evt);
            }
        });

        Listadooo4.setText("Nombre:");

        tAcumulado2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tAcumulado2ActionPerformed(evt);
            }
        });

        Listadooo5.setText("Descripcion:");

        tAcumulado3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tAcumulado3ActionPerformed(evt);
            }
        });

        Listadooo6.setText("Ponderacion:");

        Listadooo7.setText("Notas:");

        jButton1.setText("Seleccionar Archivo CSV");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        bCargaAlumnos.setText("Carga masiva -Alumnos-");
        bCargaAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCargaAlumnosActionPerformed(evt);
            }
        });

        jButton2.setText("Crear Actividad");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Listadooo, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addComponent(bCargaAlumnos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Listadooo4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tAcumulado1))
                            .addComponent(Listadooo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(Listadooo1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Listadooo2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tAcumulado, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Listadooo5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Listadooo6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Listadooo7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tAcumulado3)
                            .addComponent(tAcumulado2)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Listadooo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Listadooo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tAcumulado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Listadooo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Listadooo3)
                    .addComponent(bCargaAlumnos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tAcumulado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Listadooo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tAcumulado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Listadooo5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tAcumulado3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Listadooo6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Listadooo7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1))
                .addGap(10, 10, 10)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tAcumuladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tAcumuladoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tAcumuladoActionPerformed

    private void tAcumulado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tAcumulado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tAcumulado1ActionPerformed

    private void tAcumulado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tAcumulado2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tAcumulado2ActionPerformed

    private void tAcumulado3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tAcumulado3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tAcumulado3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bCargaAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCargaAlumnosActionPerformed
        // TODO add your handling code here:
        System.out.println("holaa");

        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(null);

        String filePath = fc.getSelectedFile().getAbsolutePath();
        System.out.println(filePath);

        BufferedReader reader = null;
        String line = "";



        try {
            reader = new BufferedReader(new FileReader(filePath));
            int contadorFila = 0;
            while ((line = reader.readLine()) != null) {
                if (contadorFila > 0) {
                    String[] columnas = line.split(";");

                    Alumno alumn = new Alumno(columnas[0], columnas[1],
                            columnas[2], "Ver mas Informacion.");

                    alumnos[contadorFila - 1] = alumn;

                }
                contadorFila++;

            }
            contadorAlumnos = contadorFila - 1;
            System.out.println(Arrays.toString(alumnos));
            actualizarListadoAlumnos();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_bCargaAlumnosActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
    public void actualizarListadoAlumnos() {

        if (contadorAlumnos > 0) {

            // actualizar listado
            DefaultTableModel modeloListado = (DefaultTableModel) ListadoAlumnos.getModel();
            modeloListado.setRowCount(contadorAlumnos);

            for (int i = 0; i < contadorAlumnos; i++) {
                modeloListado.setValueAt(alumnos[i].codigo, i, 0);
                modeloListado.setValueAt(alumnos[i].nombre, i, 1);
                modeloListado.setValueAt(alumnos[i].apellido, i, 2);
                modeloListado.setValueAt(alumnos[i].correo, i, 3);
                modeloListado.setValueAt(alumnos[i].genero, i, 4);

            }
        }
    }
        
        
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ListadoActividades;
    private javax.swing.JTable ListadoAlumnos;
    private javax.swing.JLabel Listadooo;
    private javax.swing.JLabel Listadooo1;
    private javax.swing.JLabel Listadooo2;
    private javax.swing.JLabel Listadooo3;
    private javax.swing.JLabel Listadooo4;
    private javax.swing.JLabel Listadooo5;
    private javax.swing.JLabel Listadooo6;
    private javax.swing.JLabel Listadooo7;
    private javax.swing.JButton bCargaAlumnos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lCurso;
    private javax.swing.JTextField tAcumulado;
    private javax.swing.JTextField tAcumulado1;
    private javax.swing.JTextField tAcumulado2;
    private javax.swing.JTextField tAcumulado3;
    // End of variables declaration//GEN-END:variables
}
