/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventana;
import static Ventana.vAdminProfesores.profesores;
import static Ventana.vAdministrarCursos.cursos;
import static Ventana.vActualizarProfesor.count;
import Ventana.vLogin;
import static Ventana.vLogin.num;
import static Ventana.vLogin.num2;

/**
 *
 * @author Harold
 */
public class vModulo extends javax.swing.JFrame {

    /**
     * Creates new form vModulo
     */
    public vModulo() {
        initComponents();
        bCurso.setText(cursos[num2].nombre);
        tCursoAlumnos.setText(cursos[num2].alumnos+" Alumnos(s)");
        tCursoAlumnos.setEditable(false);
        tProf.setText("Bienvenido: "+profesores[num].nombre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ActualizarBtn = new javax.swing.JButton();
        bCurso = new javax.swing.JButton();
        tCursoAlumnos = new javax.swing.JTextField();
        tProf = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ActualizarBtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ActualizarBtn.setText("Actualizar Datos");
        ActualizarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarBtnActionPerformed(evt);
            }
        });

        bCurso.setBackground(new java.awt.Color(255, 51, 51));
        bCurso.setText(".");
        bCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCursoActionPerformed(evt);
            }
        });

        tCursoAlumnos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tCursoAlumnos.setText(".");

        tProf.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tProf.setText(".");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(bCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(tProf, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(ActualizarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(tCursoAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(127, 127, 127)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tProf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ActualizarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(80, 80, 80)
                .addComponent(bCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tCursoAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ActualizarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarBtnActionPerformed
        // TODO add your handling code here:
        boolean count=vActualizarProfesor.count;
                count= false;
        
        this.setVisible(false);
        vActualizarProfesor ap = new vActualizarProfesor();
        ap.setVisible(true);
    }//GEN-LAST:event_ActualizarBtnActionPerformed

    private void bCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCursoActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
            vCursos cr= new vCursos();
            cr.setVisible(true);
                         
    }//GEN-LAST:event_bCursoActionPerformed

    /**
     * @param args the command line arguments
     */
    

    private void formWindowClosing(java.awt.event.WindowEvent evt) {                                   
        // TODO add your handling code here:
        
        this.setVisible(false);
        vLogin log = new vLogin();
        log.setVisible(true);
    }                
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarBtn;
    private javax.swing.JButton bCurso;
    private javax.swing.JTextField tCursoAlumnos;
    private javax.swing.JLabel tProf;
    // End of variables declaration//GEN-END:variables
}
